### ISSUE TITLE
map returns CategoricalArray{Any}

### ISSUE THREAD

**Issue by nalimilan** [JuliaData/CategoricalArrays.jl#126]
`map` with `CategoricalArray` currently returns a `CategoricalArray{Any}` when the function does not return a categorical value.

For example:
```julia
map(get, categorical(1:2))
Base.collect_to!(categorical([0.0, 0.0]), (1.0 for v in 1:3), 2, 2)
```

This appears to be due to the fact that `similar(::CategoricalArray, T)` returns a `CategoricalArray{T}`, whose element type is not `T` but `CategoricalValue{T}` or `CategoricalString`. So when `collect_to!` calls `promote_typejoin(T, typeof(el))`, it tries to promote `CategoricalValue{T}` with `typeof(el)` instead of doing the more appropriate `CategoricalValue{promote_typejoin(valtype(T), typeof(el))}`, and eventually chooses `Any`.

As an exception, these do not return a `CategoricalArray{Any}`:
```julia
map(string, categorical([1]))
Base.collect_to!(categorical(["", ""]), ("a" for v in 1:2), 2, 2)
```
AFAICT this is due to the fact that the `CategoricalArray` constructor uses `CategoricalString` if the array has an `AbstractString` element type. Since `promote_type(CategoricalString, String)` gives `AbstractString`, the resulting array will be `CategoricalArray{String}`.

I can see three ways of fixing this:
- Change `similar(::CategoricalArray, T)` to return an `Array{T}` when `T` is not a categorical value. This is more correct regarding the `AbstractArray` interface. But it could be annoying in some cases where a `CategoricalArray` is more natural/efficient. Or maybe not (concrete examples are needed).
- Change `promote_jointype(S::Type{<:CategoricalValue}, T)` so that it returns `CategoricalValue{promote_typejoin(valtype(S)), T)}`.
- Implement a special method for `map`. This might be needed anyway to take advantage of the possibility of calling the function only on the levels for efficiency. But the current behavior of `similar` could be problematic elsewhere.

Whichever solution we choose, it seems that `map` should continue to return a `CategoricalArray`. Indeed `map` generally preserves the container type (e.g. for tuples), `CategoricalArray` is more efficient for repeated data, and array comprehensions are available to create arrays when explicitly needed. `broadcast` should probably also preserve the type (which it currently doesn't).

**Comment by davidanthoff** [comment]
> Change similar(::CategoricalArray, T) to return an Array{T} when T is not a categorical value. This is more correct regarding the AbstractArray interface. But it could be annoying in some cases where a CategoricalArray is more natural/efficient. Or maybe not (concrete examples are needed).

That seems the right solution to me.

> Whichever solution we choose, it seems that map should continue to return a CategoricalArray.

Really? That seems a strange goal to me. If the map produces a stream of elements that are not categorical values, then surely the result should not be a categorical array, right?

> Indeed map generally preserves the container type (e.g. for tuples)

I don't think that is so. For example, say you map over a ``BitArray`` and produce a stream of strings, then the output becomes an ``Array{String}``. The categorical case here seems pretty analogous to me.

In general it seems to me that ``similar`` should always return a ``CategoricalArray`` when ``T`` is a categorical value, and a normal ``Array`` in all other cases. That is how I do it in ``DataValueArrays`` and that seems to work well.

**Comment by nalimilan** [comment]
> Really? That seems a strange goal to me. If the map produces a stream of elements that are not categorical values, then surely the result should not be a categorical array, right?

One problem is that there's no way to create a `CategoricalValue` from e.g. a string or a number. You can only extract it from a `CategoricalArray`. So even if you want the result to be a `CategoricalArray`, you have no way to indicate that. Well, there's a solution, which is to call `map!(f, similar(x, CategoricalValue{T}), x)`. Not the end of the world I guess...

> I don't think that is so. For example, say you map over a BitArray and produce a stream of strings, then the output becomes an Array{String}. The categorical case here seems pretty analogous to me.

In some aspects it is, and in others it differs. Categorical values are just wrappers around a value of a different type, so storing a string in a `CategoricalArray{String}` is not like trying to store a string in a `BitArray` either. :-)

> In general it seems to me that similar should always return a CategoricalArray when T is a categorical value, and a normal Array in all other cases. That is how I do it in DataValueArrays and that seems to work well.

Yes, that's tempting and I'll probably end up doing that. But `DataValue` is a bit different regarding the interaction with `map`, since the user-provided function needs to return a `DataValue` anyway if you want to represent missing values. With categorical values, you can perfectly return only `String` values, and expect to get a `CategoricalArray` whose levels can very efficiently be reordered afterwards.

**Comment by nalimilan** [comment]
https://github.com/JuliaData/CategoricalArrays.jl/pull/133 changes `similar` to always return an `Array` when the requested type is not `<:Union{CatValue,Missing}`. Leaving this issue open because we need systematic tests for the behavior of `map` and `broadcast` (and ideally optimized implementations inspired by what we do for `recode`).

**Comment by jcheyns** [comment]
Not sure if this is a related issue, but consider the following:
`using DataFrames
using CSV

function sound(param::String)
    if param=="dog"
        return "woof"
    elseif param=="cat"
        return "meow"
    else
        return "tweet"
    end
end

test="A,B\n"
for i=1:500
    val=mod(i,2)==0?"dog":"cat" 
    #val=i
    test=test* "$i,$val\n"
end

dfO=CSV.read(IOBuffer(test))
println(dfOrders)
dfO[:SOUND]=map((x)->sound(x),dfO[:B])
`
This generates:
```
MethodError: no method matching sound(::CategoricalArrays.CategoricalString{UInt32})
Closest candidates are:
  sound(::String) at untitled-abf37f97431b935f47ae637137980912:5
in map at base\abstractarray.jl:1868
in _collect at base\array.jl:488
```
I do not expect to need to implement the sound function for a CategoricalString.
Am I missing something?

**Comment by nalimilan** [comment]
No, that's a different issue, and actually not a bug. You should just use `::AbstractString` in the signature (which is a good idea in general anyway).

**Comment by jcheyns** [comment]
@nalimilan thanks for that.
I have another question that migh ormight not be related, consider a case of a DataFrame where one of the columns holds an Array:
```
using DataFrames
using CSV

function foo(param::AbstractString)
    val=param=="dog"?[1,2]:[3,4]
    return val
end

test="A,B\n"
for i=1:500
    val=mod(i,2)==0?"dog":"cat"    
    test=test* "$i,$val\n"
end

dfOrders=CSV.read(IOBuffer(test))
dfOrders[:MAPPED]=map((x)->foo(x),dfOrders[:B])
print(eltypes(dfOrders))
for x in dfOrders[2,:MAPPED]
    println(x)
end
```
The mapped column is stored as Union{CategoricalArrays.CategoricalValue{Any,UInt32}, Missings.Missing} and the **_in_** approach does not work:
```
MethodError: no method matching start(::CategoricalArrays.CategoricalValue{Any,UInt32})
Closest candidates are:
  start(::SimpleVector) at essentials.jl:258
  start(::Base.MethodList) at reflection.jl:560
  start(::ExponentialBackOff) at error.jl:107
```

**Comment by nalimilan** [comment]
This one is due to the present issue. `dfOrders[:MAPPED]` should be a `Vector{Array{Any}}` rather than a `CategoricalVector{Any}`.

**Comment by jcheyns** [comment]
But does using a CategoricalVector not bring efficiency?

**Comment by nalimilan** [comment]
It depends on what you do, but storing vector entries in a `CategoricalArray` isn't really a use case which has been considered. Use `PooledArray` if performance is the main concern. With #133 that code now returns a `Vector{Vector{Int}}`, so the example works.
