### ISSUE TITLE
Package breaks if ran without inline

### ISSUE THREAD

**Issue by eperim** [JuliaData/CategoricalArrays.jl#127]
When I try to use the package in a session started with `julia --inline=no` it breaks. All errors during the tests seem to fall back to this:
```
categorical(CategoricalArrays.CategoricalArray{String,1,Int64,String,CategoricalArrays.CategoricalString{Int64},Union{}}, compress=false) R1=Int64 R2=Int64: Error During Test
  Got an exception of type MethodError outside of a @test
  MethodError: in(::CategoricalArrays.CategoricalString{Int64}, ::Base.KeyIterator{ObjectIdDict}) is ambiguous. Candidates:
    in(k, v::Base.KeyIterator) in Base at associative.jl:60
    in(x::Union{CategoricalArrays.CategoricalString{R}, CategoricalArrays.CategoricalValue{T,R} where T} where R, y) in CategoricalArrays at /Users/ericperim/.julia/v0.6/CategoricalArrays/src/value.jl:118
  Possible fix, define
    in(::Union{CategoricalArrays.CategoricalString{R}, CategoricalArrays.CategoricalValue{T,R} where T} where R, ::Base.KeyIterator)
```

Note: in order to observe this behaviour it is necessary to use `julia --inline=no test/runtests.jl`, since if you run `Pkg.test` from inside the REPL it will use the default options (`inline=yes`).

**Comment by nalimilan** [comment]
Good catch. It's funny that it happens only without inlining, but indeed it looks like this ambiguity needs to be fixed to be able to call `deepcopy` on `CategoricalArray`/`CategoricalPool`. Adding the following methods fixes the problem:
```julia
Base.in(x::CatValue, y::ObjectIdDict) = invoke(in, Tuple{Any, Base.KeyIterator}, x, keys(y))
Base.in(x::CatValue, y::Base.KeyIterator) = invoke(in, Tuple{Any, Base.KeyIterator}, x, y)
```

But I think I've found a better and simpler fix, which is to remove the offending methods. See https://github.com/JuliaData/CategoricalArrays.jl/pull/128.

**Comment by nalimilan** [comment]
Fixed by https://github.com/JuliaData/CategoricalArrays.jl/pull/128.
