### ISSUE TITLE
RFC: Merge NominalArray and OrdinalArray into CategoricalArray

### ISSUE THREAD

**Issue by nalimilan** [JuliaData/CategoricalArrays.jl#13]
The only reason for having separate `NominalArray` and `OrdinalArray` types (as well as their `Nullable` counterparts) is to return an `OrdinalValue` from the latter, which supports `<` and `>`. This does not sound worth the increased complexity. We could use a single `CategoricalArray` type, and store whether it's ordered via a `Bool` field. With branch prediction, `<` shouldn't be noticeably slower than with different types.

Incidentally, this is [what Pandas does](https://pandas-docs.github.io/pandas-docs-travis/categorical.html) as well as [MATLAB](http://fr.mathworks.com/help/matlab/categorical-arrays.html). Another advantage is that data storage formats generally don't distinguish nominal and ordinal arrays, that distinction must be added after importing data: if we use two different types, moving to ordinal requires changing the type of the array after the fact.

Before doing that change, I'd like to hear what others think of it.

**Comment by quinnj** [comment]
I'm all for it, the decrease in # of types and complexity would be great.

This is also what Feather does, with the advantage that the file metadata indicates whether the CategoricalArray will be ordered or not, so no having to change the array type after the fact. 

Happy to help make the change here since I've been around the codebase a bit now. (I have some time today to have a go at it too)

**Comment by nalimilan** [comment]
Cool. Go ahead if you have the time to. I'd have loved doing that myself as reducing complexity is quite rewarding, but let's not be too egoistic. ;-)

**Comment by nalimilan** [comment]
Hmm, I just bumped again on a comment by @dmbates saying he liked that distinction: https://github.com/JuliaStats/DataFrames.jl/pull/1008#issuecomment-236199622

Douglas, do you think merging these two types would have drawbacks? Wouldn't a single type with a boolean property suit your needs?

**Comment by quinnj** [comment]
I think his thought was more on making sure to keep the distinction between `NominalArray` and `NullableNominalArray` as opposed to any kind of distinction between ordered vs. not.

**Comment by dmbates** [comment]
@nalimilan : @quinnj is correct.  I was commenting on the ability to distinguish between what would now be `CategoricalArray`s and their `Nullable` counterparts.
