### ISSUE TITLE
Rename `get` for categorical values?

### ISSUE THREAD

**Issue by bkamins** [JuliaData/CategoricalArrays.jl#142]

**Comment by bkamins** [comment]
I wanted to discuss if we should keep `get` as a function name for accessing value wrapped in categorical value but I convinced myself that it is OK so I closed the issue.

**Comment by nalimilan** [comment]
I'm not a fan of `get`. It was chosen because that function existed for `Nullable`, but not that it's been removed we could find something else (like `unwrap`).

**Comment by ararslan** [comment]
Worth discussion, so reopening.

**Comment by bkamins** [comment]
Unwrap is OK for me (I would wait till the discussion around `coalesce` in Base settles so that we know what names are used for what there as `unwrap` was also mentioned in the discussions). I understand that we would keep the current functionality (i.e. that unwrapping a `missing` should throw an error).

**Comment by bkamins** [comment]
bump (if you prefer I can open a PR for this - but you probably have a better understanding of all the consequences of #310 to make this PR correctly)

**Comment by nalimilan** [comment]
I don't think #310 would have any consequences on this.

The difficulty is that using something other than `get` will make CategoricalArrays even less generic, unless we define that function e.g. in DataAPI. But I'm not sure other packages need a similar concept. Any ideas?

**Comment by bkamins** [comment]
I think it is the opposite: the concept of unwrapping is CategoricalArrays.jl specific.

CC the usual team: @pdeffebach @quinnj @oxinabox

**Comment by quinnj** [comment]
We currently define `unwrap` in [Tables.jl](https://github.com/JuliaData/Tables.jl/blob/master/src/tofromdatavalues.jl#L66) for unwrapping DataValues. I'd be happy to move that to DataAPI and we could use that in CategoricalArrays. I agree that `get` isn't a great method for the functionality here.

**Comment by bkamins** [comment]
Ah - interesting. It would make sense. Though, looking at the implementation we would have to change the implementation a bit as now `unwrap` seems to be DataValues targetted only but at the same time there is no restriction on type of `x`.

**Comment by nalimilan** [comment]
Ah, yes, that would make sense.

**Comment by nalimilan** [comment]
Fixed by https://github.com/JuliaData/CategoricalArrays.jl/pull/328.
