### ISSUE TITLE
cut mutates breaks input vector

### ISSUE THREAD

**Issue by Ken-B** [JuliaData/CategoricalArrays.jl#145]
I was surprised to find that `cut` mutates the input `breaks` for the interval vector when `extend=true`. (And strangely only when `breaks` is sorted.)

I would say either make a copy before mutating or document the current behaviour? 
I could make a PR for either.

MWE:
```
julia> breaks = [2,4,6];

julia> cut(collect(1:10), breaks, extend=true);

julia> breaks
5-element Array{Int64,1}:
  1
  2
  4
  6
 10
```
Cheers.

**Comment by nalimilan** [comment]
Good catch, thanks! That's just an oversight, probably because I wanted to avoid allocating copies, but in terms of performance that's really negligible. See https://github.com/JuliaData/CategoricalArrays.jl/issues/145.
