### ISSUE TITLE
CategoricalArrays without CategoricalValue

### ISSUE THREAD

**Issue by matthieugomez** [JuliaData/CategoricalArrays.jl#151]
The type CategoricalArray has two different uses:
   1. represent categorical data with a particular ordering 
   2. indicate in a `@formula` call that the variable should be treated as a set of dummies. 

I think these goals are in conflict, since one may want 2. without 1. For instance, I may want to treat year as a dummy in a regression while subsetting the dataframe to years below 1995:
```julia
using DataFrames, GLM
df = DataFrame(y = rand(100), x = rand(100), year = categorical(rand(1990:2000, 100)))
lm(@formula(y ~ x + year), df[df[:year] .<= 1995]])
# ERROR: MethodError: no method matching isless(::Int64, ::CategoricalArrays.CategoricalValue{Int64,UInt32})
```

I see two solutions
1. Have a special syntax to hint `@formula` to consider a variable as categorical, such as
   ```julia
   using GLM
   df = DataFrame(y = rand(100), x = rand(100), year = rand(1990:2000, 100))
   lm(@formula(y ~ x + c.year, df[df[:year] .<= 1995]])
   ```
   This is what Stata does. This kind of syntax would be my favorite solution, but it would require to have stricter variable names (see https://github.com/JuliaData/DataFrames.jl/issues/1348). A related solution is to support functions in formulas, i.e. ` lm(@formula(y ~ x + categorical(year), df[df[:year] .<= 1995]])` although it can get verbose with large statistical models.
2. Define a simpler version of CategoricalArray that does not return a CategoricalValue when indexed

**Comment by nalimilan** [comment]
That's really a StatsModels issue. This package is about storing categorical data, not about modeling. The fact that it allows choosing the right contrasts automatically is just a side effect. Previous discussions happened at https://github.com/JuliaData/DataFrames.jl/issues/867, but the current issue is https://github.com/JuliaStats/StatsModels.jl/issues/25. Though we might want to use a different syntax, e.g. simply by specfying contrasts manually.

**Comment by matthieugomez** [comment]
The more general issue is that one may want a type with the internal representation of categorical vector but with the same API as a usual vector.
For instance, sorting a vector of strings is much faster if the vector is stored as a CategoricalVector. But using this internal representation requires the user to change the API.

I think the internal representation (i.e. storing a vector as refs and pools) should be decoupled from the CategoricalValue API. Note that this is what R does: vector of strings are always stored using a refs/pools. Converting a vector of strings to a factor only changes the API, not the internal representation.

**Comment by nalimilan** [comment]
Yes, but CategoricalArrays have been designed from the start as a type to store categorical data, not just as a trick to ensure efficiency. See https://github.com/JuliaComputing/PooledArrays.jl for a different approach. Also, since https://github.com/JuliaData/CSV.jl/pull/204 strings read from CSV files are interned, so you don't really need to use `CategoricalArray` to save space.

**Comment by matthieugomez** [comment]
Thanks. Are PooledArrays as performant as CategoricalArrays with missing values?

**Comment by nalimilan** [comment]
No idea. I guess it really depends on what you do with them anyway.

**Comment by matthieugomez** [comment]
With all the optimizations in DataFrames that specifically target CategoricalArrays, is not it the time to revisit this issue? Again, it would be nice to have something as efficient as CategoricalArray but that behaves exactly like a vector.
One solution would be to define traits shared by CategoricalArrays and PooledArrays so that optimizations in DataFrames can be applied to both.

**Comment by nalimilan** [comment]
We don't really need traits. We can either hardcode `Union{CategoricalArray,PooledArray}` (if code can be shared in a single method), or we can define separate methods in DataFrames (since missing values handling is different, maybe sharing the same function won't be practical). Anyway it should be quite easy to do now that the code exists for CategoricalArrays.

**Comment by matthieugomez** [comment]
Maybe, a better solution would be to create a type as close as possible to CategorigalVector without CategoricalValue (in particular with the same handling of missing value). You know this much better than me, but it sounds like it would avoid code duplication.

**Comment by nalimilan** [comment]
That would take much more work than simply adapting the grouping method in DataFrame.

**Comment by matthieugomez** [comment]
Ok!

**Comment by matthieugomez** [comment]
Awesome
