### ISSUE TITLE
Getting CategoricalValue from a pool

### ISSUE THREAD

**Issue by bkamins** [JuliaData/CategoricalArrays.jl#154]
Assume we have a categorical array `c` that has a level that has a value `v`. In order to get a `CategoricalValue` corresponding to this value `v` I write:
```
c.pool[get(c.pool, v)]
```
but it seems a bit cumbersome and uses access to `pool`. Is there a better way to do it? If not I think it would be good to have one.

The use case is for example an ordered categorical array in which we want to filter values greater than some level using the order defined in this array. To do this you have to compare the values in this array to a `CategoricalVale` that is this specific level.

**Comment by nalimilan** [comment]
Good question. I guess we could add a `CategoricalValue` constructor which would take the pool and the value. It's always annoying that one cannot construct a `CategoricalValue` just from its value.

**Comment by bkamins** [comment]
This is what I want 😄. However, if I understand it correctly pool is not part of the API - right? So we should rather have two constructors:

* one acccepting `CategoricalValue` from which pool is taken;
* one acccepting `CategoricalArray` from which pool is taken.

Or I am mistaken and pool is directly exposed to the user?

**Comment by nalimilan** [comment]
Yeah, at least the pool is lower-level API. I guess we could do that. But I wonder whether it wouldn't be more appropriate to define `<(x::CategoricalValue{T}, y::T)`. That sounds quite natural, and would be much more convenient than manually creating a `CategoricalValue`.

**Comment by bkamins** [comment]
The problem with defining `<(x::CategoricalValue{T}, y::T)` is actually the reason why I have opened the issue altogether.

The problem is that `CategoricalString` is `AbstractString` so then there would be ambiguity whether comparison should use string comparison or categorical comparison. That is: currently `<` works for `CategoricalString` when comparing with a string, so this what you propose would be breaking (also this change would mean that `CategoricalString` does not always behave as string in function operating on strings), so 😕.

For other categorical values this will be fine.

**Comment by nalimilan** [comment]
That sounds fine to me. Anyway `<(::CategoricalString, ::CategoricalString)` is already defined and disagrees with the standard `AbstractString` method. I'm not very happy with the fact that `<` is defined on strings for this reason (i.e. if you accidentally convert a categorical variable to a string variable the ordering will silently be wrong), but that's how it works...

**Comment by bkamins** [comment]
OK. I am making a PR for `<` and `isless` for completeness.

**Comment by nalimilan** [comment]
Hopefully no longer needed thanks to https://github.com/JuliaData/CategoricalArrays.jl/pull/156.
