### ISSUE TITLE
Uppdate of CI scripts

### ISSUE THREAD

**Issue by bkamins** [JuliaData/CategoricalArrays.jl#157]
@nalimilan `appveyor.yml` and `.travis.yml` need updating for Julia 1.0 (in particular Appveyor CI fails on Julia 1.0 in current configuration), but I was not sure which versions of Julia you want to test against so I am opening an issue.

**Comment by nalimilan** [comment]
I guess 0.7, 1.0 and nightlies?

**Comment by bkamins** [comment]
I have added them to #156 to ensure proper testing.
