### ISSUE TITLE
Current version of CategoricalArrays.jl doesn't work correctly on Julia 0.6

### ISSUE THREAD

**Issue by ufechner7** [JuliaData/CategoricalArrays.jl#165]
The current version of Categorical Arrays does not precompile correctly on Julia 0.6:
```
julia> using CSV
INFO: Precompiling module CSV.
WARNING: static parameter R does not occur in signature for catvaluetype at /home/ufechner/.julia/v0.6/CategoricalArrays/src/value.jl:52.
The method will not be callable.

julia> 
```
Can you please set the version limits such that installing CategorialArrays on Julia 0.6.x continues to work without error?

**Comment by nalimilan** [comment]
Good catch. Unfortunately we had dropped Julia 0.6 from CI but forgot to bump REQUIRES. See https://github.com/JuliaLang/METADATA.jl/pull/18700.
