### ISSUE TITLE
skipmissing does not preserve levels

### ISSUE THREAD

**Issue by ablaom** [JuliaData/CategoricalArrays.jl#180]
`skipmissing` maps `CategoricalArrays` to `CategoricalArrays` but levels not assumed in the original array are lost:

````
julia> v = categorical([missing, "foo", "bar"])
3-element CategoricalArray{Union{Missing, String},1,UInt32}:
 missing
 "foo"  
 "bar"  

julia> w = v[1:2]
2-element CategoricalArray{Union{Missing, String},1,UInt32}:
 missing
 "foo"  

julia> levels(w)
2-element Array{String,1}:
 "bar"
 "foo"

julia> levels(skipmissing(w))
1-element Array{CategoricalString{UInt32},1}:
 "foo"

julia> levels(skipmissing(w)) == levels(w)
false
````

**Comment by ablaom** [comment]
Furthermore, to be consistent with behaviour in ordinary arrays, `skipmissing` should return a `CategoricalArray` of type `T` instead of type `Union{Missing, T}`. That is, `skipmissing` should purify the eltype as well as the elements.

**Comment by nalimilan** [comment]
`skipmissing` simply returns an iterator over the non-missing values in the input collection. The fact that `levels` behaves that way is due to the fallback method for collections. I guess we could add a special method to return the levels of the parent array. But can you describe your use case?

**Comment by ablaom** [comment]
Thanks for taking a look at this! To be more explicit about the problem:

````
julia> v = categorical([missing, 'a', 'b', 'c'])
julia> w = v[1:3]
3-element CategoricalArray{Union{Missing, Char},1,UInt32}:
 missing
 'a'    
 'b'    

julia> levels(w)
3-element Array{Char,1}:
 'a'
 'b'
 'c'

julia> levels(skipmissing(w))
2-element Array{CategoricalValue{Char,UInt32},1}:
 'a'
 'b'
````
To my way of thinking this is behaviour is just plain wrong.

My use case is in machine learning. In testing a learner with categorical inputs, you get into trouble if you fit your learner to data that doesn't have all the levels encountered in the test set, unless you use categorical arrays (or something similar) which remember all the levels even when you select a train subset of your data array. But we may also need to ignore missing data and don't want to throw out the baby (the levels) with the bath water. 

BTW, I don't see that the problem is to modify `levels`. It seems to me one needs to overload the `skip missing` method for `CategoricalArrays`.

**Comment by ablaom** [comment]
Oh hang on, my mistake. `skipmissing` returns an ordinary array not a `CategoricalArray`, so the behaviour is as expected after all. Let me rethink this and perhaps make a feature request.

**Comment by nalimilan** [comment]
On master at least levels are preserved if you call `collect`, since it now returns a `CategoricalArray`. We could add a special method for `SkipMissing`, but I'm not sure it's a good idea since many other iterators could deserved the same treatment.
```julia
julia> v = categorical([missing, 'a', 'b', 'c'])
4-element CategoricalArray{Union{Missing, Char},1,UInt32}:
 missing
 'a'
 'b'
 'c'

julia> w = v[1:3]
3-element CategoricalArray{Union{Missing, Char},1,UInt32}:
 missing
 'a'
 'b'

julia> levels(w)
3-element Array{Char,1}:
 'a'
 'b'
 'c'

julia> levels(skipmissing(w))
2-element Array{CategoricalValue{Char,UInt32},1}:
 'a'
 'b'

julia> collect(skipmissing(w))
2-element CategoricalArray{Char,1,UInt32}:
 'a'
 'b'

julia> levels(collect(skipmissing(w)))
3-element Array{Char,1}:
 'a'
 'b'
 'c'

```

**Comment by nalimilan** [comment]
Something we could do is define `levels(::AbstractArray{<:CategoricalValue})` to return the levels of the values if they all have the same pool, or possibly even merge levels if there are different pools. The code for this already exists.
