### ISSUE TITLE
What's the right way to force elements into pool during cat vector construction?

### ISSUE THREAD

**Issue by ablaom** [JuliaData/CategoricalArrays.jl#190]
Occasionally I want to construct a categorical vector but force the pool to contain certain elements that are possibly are missing from the raw vector. For example, an ML classification algorithm predicts cat vectors on new input data, but I want its pool to coincide with that of the training target, which is generally larger. I can always append the missing elements to the constructed cat vector, and then remove them again, (or, worse, directly alter the pool attribute of elements and the vector) but this is not ideal.  

What is the "right" way to do this? Would you consider adding a kwarg or optional argument to the constructor `categorical` to do this (eg, `categorical([:x, :y], include=[:x, :z])`) gets a pool of `[:x, :y, :z]`)?

**Comment by nalimilan** [comment]
So IIUC you want to avoid making a copy of the vector, but just add the levels to the pool? You can do that manually by copying the pool and building a new `CategoricalVector` based on the references (without copy) and the new pool.

I'm not sure we can make `categorical` do that since it's supposed to return a new copy. Or maybe we could provide a function to copy the pool.

**Comment by ablaom** [comment]
Actually, I'm not adding to the pool of an existing categorical vector (although constructing one could be the first step). Rather, I'm constructing the vector and the (enlarged) pool simultaneously. Here's what I do now:
```
julia> raw = [:x, :y, :y, :x]
julia> classes = [:x, :y, :z, :w]  # superset of unique(raw)
julia> v = categorical(vcat(raw, classes))[1:length(raw)]
4-element CategoricalArray{Symbol,1,UInt32}:
 :x
 :y
 :y
 :x

julia> levels(v)
4-element Array{Symbol,1}:
 :w
 :x
 :y
 :z
```
How can I do this better and in a non-brittle way?

**Comment by nalimilan** [comment]
Why not just call `levels!(categorical(raw), classes)`? That will be very efficient.

**Comment by ablaom** [comment]
Perfect!

Thanks.
