### ISSUE TITLE
Stackoverflow errror with categorical of Any

### ISSUE THREAD

**Issue by tlienart** [JuliaData/CategoricalArrays.jl#220]
### context

In MLJBase we use the following function:

```julia
classes(p::CategoricalPool) = [p.valindex[p.invindex[v]] for v in p.levels]
```

The justification for this function is a bit beside the point but  can be read [here](https://github.com/alan-turing-institute/MLJBase.jl/blob/c69fd55dfbc9cef3908f661e440d430f9d91b71f/src/data.jl#L117-L141) if desired.

The  following errors with stackoverflow (in some cases it even kills the Julia session but that's irrelevant)

```julia
c = categorical(Any[collect("abcabcabc")...])
classes(c[1].pool)
```

### mwe

The problem here is with the list comprehension over `p.valindex` when these are `CategoricalValue{Any...}`. Here's a very simple MWE

```julia
c = categorical(Any[collect("abcabcabc")...])
p = c.pool
[p[1], p[2]] # crashes Julia
```

Note however that if it's not `Any`, it works fine:

```julia
c = categorical(collect("abcabcabc"))
p = c.pool
[p[1], p[2]]
```

I guess there's an ambiguity when there's `Any` but either

* it should not fail, or
* it should be caught earlier explaining a workaround

### additional infos

Stacktrace for the stackoverflow earlier is reproduced below:

```
ERROR: StackOverflowError:
Stacktrace:
 [1] ht_keyindex(::Dict{Any,UInt32}, ::Char) at ./dict.jl:289
 [2] in(::Char, ::Base.KeySet{Any,Dict{Any,UInt32}}) at ./dict.jl:546
 [3] issubset(::Array{Any,1}, ::Base.KeySet{Any,Dict{Any,UInt32}}) at ./abstractset.jl:268
 [4] ⊈ at ./abstractset.jl:319 [inlined]
 [5] get!(::CategoricalPool{Any,UInt32,CategoricalValue{Any,UInt32}}, ::CategoricalValue{Any,UInt32}) at /Users/tlienart/.julia/packages/CategoricalArrays/kxnZh/src/pool.jl:197
 [6] get!(::CategoricalPool{Any,UInt32,CategoricalValue{Any,UInt32}}, ::CategoricalValue{Any,UInt32}) at /Users/tlienart/.julia/packages/CategoricalArrays/kxnZh/src/pool.jl:204 (repeats 25987 times)
 [7] setindex!(::CategoricalArray{Any,1,UInt32,Any,CategoricalValue{Any,UInt32},Missing}, ::CategoricalValue{Any,UInt32}, ::Int64) at /Users/tlienart/.julia/packages/CategoricalArrays/kxnZh/src/array.jl:337
 [8] collect_to_with_first! at ./array.jl:643 [inlined]
 [9] collect(::Base.Generator{Array{Any,1},var"#3#4"{CategoricalPool{Any,UInt32,CategoricalValue{Any,UInt32}}}}) at ./array.jl:625
 [10] classes(::CategoricalPool{Any,UInt32,CategoricalValue{Any,UInt32}}) at ./REPL[2]:1
```

### why?

In case there's curiosity in where this issue came up, basically we have this "coercion" mechanism in [ScientificTypes.jl](https://github.com/alan-turing-institute/ScientificTypes.jl) which allows a user to specify how data should be interpreted more or less irrespective of how the data is currently encoded.
An example where the `Any` thing can come up is if the user reads a CSV file with `readdlm` which spews out an array of `Any` when it meets non numerics; the user may still want to specify that column X is a Continuous (that handles fine) or a Multiclass (that's the one which causes the bug above). A workaround is to treat a vector of Any that should be interpreted as a Multiclass as a String (https://github.com/alan-turing-institute/ScientificTypes.jl/pull/39).

But  even then, I thought it was best if this was reported here anyway as it might help improve the code

**Comment by nalimilan** [comment]
Indeed. I have a simple fix at #221.

BTW, the definition of `classes` would better avoid accessing internal fields. It can be rewritten as simply as `classes(p::CategoricalPool) = [p[i] for i in CategoricalArrays.order(p)]`. Also, the sentence "In particular, while `x in classes(x)` is always true, `x in x.pool.levels` is not true." in the docstring is incorrect, as categorical values compare equal to their unwrapped equivalent. So I'm not sure why `classes` is needed.

Likewise, the definition of `int` can be simplified like this: `int(x::CategoricalElement) = CategoricalArrays.order(x.pool)[x.level]`. This is documented in the manual IIRC.

**Comment by tlienart** [comment]
Thanks for this Milan, and I'll PR your suggestions to mljbase, thanks for taking the time!

**Comment by tlienart** [comment]
Actually your suggested re-implementation of `classes` is not equivalent, MWE below for what goes wrong (I  could open this in another issue if deemed worthy).

```julia
using CategoricalArrays

# Your implementation

classes(p) = [p[i] for i in CategoricalArrays.order(p)]
V = categorical(collect("asqfasqffqsaaaa"))
A, S, Q, F = V[1:4]
pool_ = A.pool # [a, f, q, s]
levels_ = levels(pool_) # [a, f, q, s]
classes(pool_) == [A, F, Q, S] # ok
levels!(V, reverse(levels(V)))
levels_ = levels(pool_) # [s, q, f, a] 
classes(pool_) # [f, a, s, q] <---- not ok

# Ours

classes(p) = [p.valindex[p.invindex[v]] for v in p.levels]
V = categorical(collect("asqfasqffqsaaaa"))
A, S, Q, F = V[1:4]
pool_ = A.pool # [a, f, q, s]
levels_ = levels(pool_) # [a, f, q, s]
classes(pool_) == [A, F, Q, S] # ok
levels!(V, reverse(levels(V)))
levels_ = levels(pool_) # [s, q, f, a] 
classes(pool_) # [s, q, f, a] <---- ok
```

**Comment by nalimilan** [comment]
Ah, sorry, I should have checked better. The correct definition is this:
```julia
classes(p) = [p[i] for i in invperm(CategoricalArrays.order(p))]
```
There are probably a more efficient ways to do this (avoiding an allocation), but it should be faster than your current solution which performs a dict lookup.

Out of curiosity, why do you need this instead of just `levels`?

**Comment by tlienart** [comment]
Thanks a lot for this (and for the fix you just merged). 

I'll relay your original suggestion to Anthony that `levels` may in fact just be what we want (I don't work that much on MLJBase so I don't know the whys behind all choices); possibly we would still name it "classes" as I think the function name works well with the ML applications. 

Unrelated: I didn't know of the `invperm` function 👍
