### ISSUE TITLE
ERROR: LoadError: LoadError: UndefVarError: tostr_sizehint not defined

### ISSUE THREAD

**Issue by goedman** [JuliaData/CategoricalArrays.jl#230]
Above error (last line in src/depreciations.jl) fails DataFrames on Julia 1.4-DEV. After some testing on Julia 1.3 I don't think Julia 1.3 needs it. I don't have Julia 1.0 to 1.2 installed, but wonder if it is still needed.

**Comment by chriscoey** [comment]
This is causing me headaches too, thanks for reporting

**Comment by goedman** [comment]
Thank you! I'll close this issue after the fix is merged.

**Comment by gaelforget** [comment]
Seem to have the same issue (maybe related: https://github.com/JuliaLang/julia/pull/33953 and https://github.com/JuliaData/CategoricalArrays.jl/pull/229)

**Comment by nalimilan** [comment]
Funny, I didn't expect so many people to use Julia 1.4. :-)

**Comment by gaelforget** [comment]
> Funny, I didn't expect so many people to use Julia 1.4. :-)

I only use it for CI and noticed the issue because https://travis-ci.org/gaelforget/IndividualDisplacements.jl failed with `nightly`

Thanks for the fix (will rerun my pkg CI once 0.7.4 is registered)

**Comment by UpAndComing915** [comment]
Guys, I'm fairly new to Julia, what exactly is the fix? Is there something I can copy & paste. And would I run it in Terminal?

**Comment by bkamins** [comment]
What is the version of Julia, CSV, DataFrames, and CategoricalArays you are using?
(use `versioninfo()` and `using Pkg; Pkg.status()` to get this information)

Thank you!

**Comment by UpAndComing915** [comment]
<img width="1145" alt="Screen Shot 2020-09-12 at 12 55 19 PM" src="https://user-images.githubusercontent.com/71160522/93002863-37e3d900-f4f7-11ea-9e02-e729e9425a05.png">

**Comment by bkamins** [comment]
You have CSV version 0.3.1 installed - it is grossly outdated and unsupported. The current version is 0.7.7.
Similarly DataFrames.jl - you have version 0.13.1 and has not been supported for several years now. The current version is 0.21.7. Similarly with ECharts.jl.

Install current version of DataFrames.jl by writing `add DataFrames@0.21` and tell me what error you get.

**Comment by UpAndComing915** [comment]
<img width="1142" alt="Screen Shot 2020-09-12 at 5 40 31 PM" src="https://user-images.githubusercontent.com/71160522/93006886-21517800-f51f-11ea-9799-977f0bf0f33a.png">
>

**Comment by UpAndComing915** [comment]
All right, I got it.
After trying
`Pkg.add(Pkg.PackageSpec(name="DataFrames", version="0.21.0"))`
there appeared to be an issue with ECharts, obviously being outdated, so I used

`Pkg.add(Pkg.PackageSpec(name="ECharts", version="0.4.0"))` 
`Pkg.add(Pkg.PackageSpec(name="DataFrames", version="0.21.0"))`, 

but I STILL got some error with ECharts, so I had to remove it first:
`Pkg.rm("ECharts");  recursive=true`
And finally, DataFrames updated, and now so are the rest of my packages :)
Thank you very much!

**Comment by bkamins** [comment]
If you like ECharts.jl you need to do `add ECharts#master` or ask its maintainer to make a release (the package has not seen a release for almost a year now).
