### ISSUE TITLE
WARNING: Compat.Statistics is deprecated, use Statistics instead.

### ISSUE THREAD

**Issue by wjholden** [JuliaData/CategoricalArrays.jl#236]
https://github.com/JuliaData/CategoricalArrays.jl/blob/4ad990cc564cbea5177e3d6d7f87529e3651f972/src/extras.jl#L1

This might be nothing, so please forgive the issue if it is not useful. My machine gives a warning that Compat.Statistics is deprecated.

```
julia> using DataFrames, GLM
[ Info: Precompiling DataFrames [a93c6f00-e57d-5684-b7b6-d8193f3e46c0]
WARNING: Compat.Statistics is deprecated, use Statistics instead.
  likely near C:\Users\wjhol\.julia\packages\CategoricalArrays\u89s1\src\extras.jl:1
[ Info: Precompiling GLM [38e38edf-8417-5370-95a0-9cbb8c7f171a]
```

**Comment by nalimilan** [comment]
Thanks. See https://github.com/JuliaData/CategoricalArrays.jl/pull/238.
