### ISSUE TITLE
ordered() -> isordered()

### ISSUE THREAD

**Issue by alyst** [JuliaData/CategoricalArrays.jl#24]
Would it be more idiomatic to rename `ordered()` into `isordered()`?

**Comment by nalimilan** [comment]
Good question. I had thought about it, but it seems that no `is*` function in base has a setter counterpart. So I've followed the same convention as for `levels`/`levels!`. Could you find a few examples of either convention? We should probably discuss that, like https://github.com/JuliaLang/julia/issues/16770.

**Comment by alyst** [comment]
One example is `isempty()`/`empty!()`, there's also `islocked()`, `iswritable()`, which should refer to `locked`/`writable` flag of an object.

With `levels()` one naturally expects that the levels are returned, with `ordered(X)` one has to remember that the flag is returned, not the ordered copy of `X`.

And another question is whether `ordered!(A, flag)` should return `A` or `flag`. I though `xxx!()` functions tend to (modify and) return the first argument. IHMO it's also more useful to have `A`-returning form as it allows constructs like `df = DataFrame(flower = ordered!(flowers), ...)` and chaining in general. It's not obvious how the flag returned by `ordered!()` could be used. Same for `levels!()`.

**Comment by nalimilan** [comment]
> And another question is whether ordered!(A, flag) should return A or flag. I though xxx!() functions tend to (modify and) return the first argument. IHMO it's also more useful to have A-returning form as it allows constructs like df = DataFrame(flower = ordered!(flowers), ...) and chaining in general. It's not obvious how the flag returned by ordered!() could be used. Same for levels!().

Yeah, why not? I didn't give much consideration to this, and indeed the current choice doesn't sound very useful. PR welcome (though you'll have to tweak a lot of tests for this...).

**Comment by nalimilan** [comment]
There's still the question of whether to use `ordered!` or `setordered!`, and same for `levels!` vs. `setlevels!`. Let's see what JuliaLang/julia#16770 gives.

Another case I just bumped into: should `droplevels!` return the new levels, or the array? For consistency with `levels!`, it should return the array. OTOH, returning the levels is slightly more useful from `droplevels!` since they are not known in advance; that said, calling `levels` is cheap. What do you think?

**Comment by alyst** [comment]
@nalimilan I think chaining of `droplevels!()` is a useful property and matches well with the other `!` methods, and one still can use `levels(droplevels!(A))`.

**Comment by nalimilan** [comment]
So.. time for another PR?

**Comment by alyst** [comment]
Actually, #26 automatically modified `droplevels!(A)` behaviour, if you mean it.

**Comment by nalimilan** [comment]
Ah, indeed, now I see you mentioned it. So all is well.
