### ISSUE TITLE
Complete Nullable API

### ISSUE THREAD

**Issue by alyst** [JuliaData/CategoricalArrays.jl#25]
It would be nice to have `padnull()`, `anynull()` etc methods for `NullableCategoricalArray`, and also to maintain the API parity with `NullableArrays` in the long term. There are 3 possibilities:
- CategoricalArrays require NullableArrays and extend NullableArrays methods for NullableCategoricalArray
- NullableArrays require CategoricalArrays and implement nullable API for `NullableCategoricalArray` (the type definition still stays in the `CategoricalArrays`),
- the new package `NullableCategoricalArrays.jl` that requires both `NullableArrays` and `CategoricalArrays`. That way the requirements could be made really fine grained.
- ...?

To me the second option makes more sense:
- if one wants to work with nullables, it's very likely that he/she would like to have nullable support for categorical arrays
- `CategoricalArrays` is a smaller package that has minimal number of dependencies
- it's also better for maintenance and version updates to have all methods defined in one package

**Comment by nalimilan** [comment]
Option 1 sounds better to me. CategoricalArrays already needs NullableArrays for tests, and `NullableCategoricalArray` is already a kind of optimized version of `NullableArray` for categorical data. People working with categorical data will likely need nullable arrays, but it's less obvious in the other direction. I don't think @davidgold would be OK with adding a new dependency to NullableArrays. :-)

Though these functions are quite essential and we could imagine moving them into Base at some point, which would allow dropping the dependency.

**Comment by alyst** [comment]
@nalimilan Ah, if `NullableArrays` is already required, then the only concern is the synchronization of APIs.

**Comment by nalimilan** [comment]
It's only required for testing at the moment, but that's already an indication of a relatively tight coupling.

**Comment by nalimilan** [comment]
No longer applies now that we've moved to Nulls.
