### ISSUE TITLE
Handle heterogeneous string level types

### ISSUE THREAD

**Issue by bkamins** [JuliaData/CategoricalArrays.jl#255]
Currently on #master we have:
```
julia> using CategoricalArrays
[ Info: Precompiling CategoricalArrays [324d7699-5711-5eae-9e2f-1d82baa6b597]

julia> x = categorical(["a", "b"])
2-element CategoricalArray{String,1,UInt32}:
 "a"
 "b"

julia> y = categorical([SubString("a",1,1), SubString("b",1,1)])
2-element CategoricalArray{SubString{String},1,UInt32}:
 "a"
 "b"

julia> z = categorical([SubString("a",1,1), "b"])
2-element CategoricalArray{AbstractString,1,UInt32}:
 "a"
 "b"
```
I feel that this is not optimal especially as:
```
julia> v = [SubString("a",1,1), "a"]
2-element Array{AbstractString,1}:
 "a"
 "a"

julia> typeof(v[1])
SubString{String}

julia> typeof(v[2])
String

julia> c = categorical(v)
2-element CategoricalArray{AbstractString,1,UInt32}:
 "a"
 "a"

julia> typeof(get(c[1]))
SubString{String}

julia> typeof(get(c[2]))
SubString{String}
```

Maybe we should always cast `AbstractString` to `String`?

**Comment by bkamins** [comment]
And we have the same situation with other types like:
```
julia> h = categorical(Real[1, 1.0])
2-element CategoricalArray{Real,1,UInt32}:
 1
 1
```
but here it is probably not that problematic (and I would say is acceptable - especially that it is probably not something that will be common in practice, while for strings it is common to have `String` and `SubString`)

**Comment by nalimilan** [comment]
Yeah, we can say that since the number of levels should be low it doesn't make sense to keep `SubStrings`. That reasoning may hold for any `AbstractString`, though purists will say that some string types may not be Unicode.

**Comment by bkamins** [comment]
> though purists will say that some string types may not be Unicode.

Good point, then maybe just convert `SubString{String}` to `String`? I think other string types are so rare that we can leave them as is.
