### ISSUE TITLE
Make `fill(::CategoricalValue, ::Integer)` return a `CategoricalArray`

### ISSUE THREAD

**Issue by nalimilan** [JuliaData/CategoricalArrays.jl#257]
This would allow writing `fill(v, n)` instead of `fill!(Tables.allocatecolumn(typeof(v), n), v)`. The `fill` docstring doesn't mention that it should return an `Array` so it should be OK. See https://github.com/JuliaData/DataFrames.jl/pull/2165#discussion_r403330789.

**Comment by bkamins** [comment]
`Tables.allocatecolumn` is very easy to forget to do (especially in user's code) so :+1: .

**Comment by nalimilan** [comment]
Closed by https://github.com/JuliaData/CategoricalArrays.jl/pull/259.
