### ISSUE TITLE
Paper to cite?

### ISSUE THREAD

**Issue by ablaom** [JuliaData/CategoricalArrays.jl#267]
Writing a paper on MLJ design and wanted to check if you had a preferred way for us to cite the CategoricalArrays project. 

If not, we can just cite the repo. In that case, is authors = "Milan Bouchet-Valat etal" okay?

**Comment by nalimilan** [comment]
I haven't really thought about it until now. I'd say what you suggest for authors is OK. I guess I could register the package in Zenodo if that's helpful for you.

**Comment by ablaom** [comment]
I've just "cited" the repo. Let me know if you do register with Zenodo and I will update the preprint.
