### ISSUE TITLE
Should a CategoricalValue be a Number?

### ISSUE THREAD

**Issue by juliohm** [JuliaData/CategoricalArrays.jl#268]
I am writing some methods that take general `::Number` as arguments. I wonder if it makes sense to make a `CategoricalValue` a subtype of `Number`? What are your thoughts on this?

**Comment by bkamins** [comment]
If your methods allow `CategoricalValue` I would use an explicit `Union` on them or have a specific methods accepting `CategoricalValue`.

**Comment by juliohm** [comment]
Do you think this is the better way forward? I personally think that if categorical values are indeed numbers, putting a super type on them can save a lot of manual work from the user side. We could pass categorical values to existing implementations expecting numbers and adjust when strictly needed. In my use case, there is no need for adjustment as I am only using the `==` operator to compare two categorical values, which is also defined for numbers in general.

**Comment by juliohm** [comment]
To give you some context, I will be releasing a new version of LossFunctions.jl soon with better support for CategoricalArrays.jl. Take for example the misclassification loss:

```
value(l::MissclassLoss, y::Number, yhat::Number) = value(l, y == yhat)
value(l, agreement) = ifelse(agreement, 0, 1)
```

In this specific case I only needed to add the Union type as you suggested:

```
const CV = Union{CategoricalValue,Number}

value(l::MisclassLoss, y::CV, yhat::CV) = value(l, y == yhat)
```

This union type hanging around seems a bit unnecessary.

**Comment by juliohm** [comment]
Furthermore, I needed to depend explicitly on CategoricalArrays.jl just to make the name `CategoricalValue` available, to create this Union type.

**Comment by bkamins** [comment]
But if you need only `==` then why do you want to add a restriction `::Number`? You could accept `::Any` there as well.

My question is that normally you assume that `::Number` supports more operations than just `==` (like `+`, `*`).

**Comment by juliohm** [comment]
> But if you need only `==` then why do you want to add a restriction `::Number`? You could accept `::Any` there as well.

I am a bit afraid of declaring methods with `Any`, but I will take a look. We have many variants of the function `value` for example with `Number` with `Vector{<:Number}` and so on. So it is hard to leave it as `Any`, unless I use the `Any` here as the replacement for `Number`, which is the concept I actually need. I don't want to evaluate losses with some arbitrary user types for example.

> My question is that normally you assume that `::Number` supports more operations than just `==` (like `+`, `*`).

Do you know if this set of assumptions for `Number` is documented somewhere? I tend to think that the original idea behind this type is to have any kind of number, not necessarily implementing `*` or `+`. For more specific number types from a more specific set like the N, Z, R, we have more operations defined.

**Comment by juliohm** [comment]
To me the concept of `Number` is the general concept to hold numerical values. And categorical values are numbers in this sense. What is the problems you are seeing regarding making `CategoricalValue <: Number`?

**Comment by bkamins** [comment]
But why do you see `CategoricalValue` a numerical value? Consider this example:
```
julia> x = categorical(["apple", "banana", "orange"])
3-element CategoricalArray{String,1,UInt32}:
 "apple"
 "banana"
 "orange"

julia> x[1]
CategoricalValue{String,UInt32} "apple"
```

why do you see `x[1]` to be numerical?

**Comment by juliohm** [comment]
That is a good question. I don't have a good explanation for it since the definition of `Number` itself isn't clear to me. Perhaps my intuition is aligned with the scientific type instead? https://github.com/alan-turing-institute/ScientificTypes.jl#1-scientific-types

CategoricalVaue is certainly a `Multiclass` or `OrderedFactor` so I think what I really want is a parent type for both `Finite{N}` and `Infinite` scientific types. I could perhaps replace `Number` with `NT = Union{Finite{N} where N,Infinite}` and dispatch on that instead. So my only dependency would be `ScientificTypes.jl`. What do you think? Does that make sense? Is it a better approach than making CategoricalValue a subtype of Number?

**Comment by juliohm** [comment]
Yes, I think one way forward is to introduce some scitype traits and implement loss functions using them:

```julia
value(loss, y, yhat) where {isnumerical(y),isnumerical(yhat)}
isnumerical(x) = scitype(x) <: Union{Infinite,Finite{N} where N}
```
or something along these lines.

**Comment by juliohm** [comment]
I think the trait that I am after is actually "numerical scalar", which I think can be described as the Union above with Finite and Infinite. The only missing component is the trait-sugar-syntax, which will be available in a package soon :pray:

**Comment by bkamins** [comment]
I would wait here and see what other people from JuliaData think.

**Comment by juliohm** [comment]
@nalimilan what is your opinion on this issue?

**Comment by nalimilan** [comment]
Sorry I hadn't noticed this. `CategoricalValue` is definitely *not* a number. The whole point of this type is to distinguish it from values which should be treated as numeric.

**Comment by nalimilan** [comment]
> CategoricalVaue is certainly a `Multiclass` or `OrderedFactor` so I think what I really want is a parent type for both `Finite{N}` and `Infinite` scientific types. I could perhaps replace `Number` with `NT = Union{Finite{N} where N,Infinite}` and dispatch on that instead. So my only dependency would be `ScientificTypes.jl`. What do you think? Does that make sense? Is it a better approach than making CategoricalValue a subtype of Number?

I think that makes sense. Unfortunately that requires you to depend on CategoricalArrays (indirectly via ScientificTypes.jl). Hopefully at some point optional dependencies will be supported by Julia.

**Comment by juliohm** [comment]
Could you please share why you think a CategoricalValue is not a Number? To me it seems reasonable to make it a subtype and solve a bunch of these issues we are brainstorming currently.

**Comment by juliohm** [comment]
Saw your answer in the other issue on LossFunctions.jl

**Comment by juliohm** [comment]
I understand that the consensus here is that categorical values shouldn't be numbers, right? I will close the issue for now, but feel free to reopen in case you change mind.

**Comment by ablaom** [comment]
> CategoricalVaue is certainly a `Multiclass` or `OrderedFactor` so I think what I really want is a parent type for both `Finite{N}` and `Infinite` scientific types. I could perhaps replace `Number` with `NT = Union{Finite{N} where N,Infinite}` and dispatch on that instead. So my only dependency would be `ScientificTypes.jl`. What do you think? Does that make sense? Is it a better approach than making CategoricalValue a subtype of Number?

Minor note: You would actually need `MLJScientificTypes` because `ScientificTypes` doesn't actually implement a scientific type convention any longer, just provides the types (you would have `scitype(categorical(1:3)) == Unknown` without importing `MLJScientificTypes`).
