### ISSUE TITLE
cut usage

### ISSUE THREAD

**Issue by yakir12** [JuliaData/CategoricalArrays.jl#270]
I end using this cut function quite a bit. But I need the bins to be numeric instead of strings. May I suggest you make sue of `Intervals`? This way you'll be able to define it better, and people will be able to make use of the bins as "numbers".
Alternatively, move `cut` to Statistics or StatsBase for binning in histograms...

**Comment by nalimilan** [comment]
Unfortunately we can't put this in StatsBase since it has to depend on CategoricalArrays to return a `CategoricalArray` (as `Vector{String}` would be very inefficient and lose the ordering). Can you give more details about what you have in mind with intervals?

**Comment by yakir12** [comment]
Currently cut return a categorical array of Strings. Here, I suggest returning a categorical array of `IntervalSets.Interval{:closed,:open}`. They capture exactly what your bins do, but they are also useful in terms of calculating things. I mean, the only thing you can do with the strings is display them. To actually calculate anything you'd need to convert them to numbers somehow.

But to be honest, this came up only because I needed the functionality of `cut` independently of the fact that the result of `cut` is a categorical array. It's just useful to be able to categorize a set of continuous values into discrete ordinal groups.

**Comment by nalimilan** [comment]
That sounds like an interesting option to allow, but as a default I'm afraid it will be confusing for most intended users. The printing of intervals isn't very user-friendly, and I want people to be able to do things like `x .== "[1, 2)"` without having to learn about intervals.

**Comment by yakir12** [comment]
I totally understand.
