### ISSUE TITLE
Missing method for CategoricalArray initialization from its fields

### ISSUE THREAD

**Issue by evetion** [JuliaData/CategoricalArrays.jl#288]
I wanted to construct a `CategoricalArray` from already flagged data (an Array of UInt data and a mapping), but it seems I can't initialize the struct from its fields. Using CategoricalArrays v0.8.1:

```julia
julia> c = CategoricalVector(["test"])
1-element CategoricalArray{String,1,UInt32}:
 "test"

julia> CategoricalVector(c.refs, c.pool)
ERROR: MethodError: no method matching CategoricalArray{T,1,V,C,U,U1} where U1 where U where C where V where T(::Array{UInt32,1}, ::CategoricalPool{String,UInt32,CategoricalValue{String,UInt32}})
Closest candidates are:
  CategoricalArray{T,1,V,C,U,U1} where U1 where U where C where V where T(::AbstractArray{T,1}; levels, ordered) where T at /Users/evetion/.julia/packages/CategoricalArrays/nd8kj/src/array.jl:262
Stacktrace:
 [1] top-level scope at REPL[10]:1
```

**Comment by bkamins** [comment]
You are trying to use the constructor, and it you look at the inner-constructor of the stuct you will see that the way to do it is:
```
julia> CategoricalArray{String,1}(c.refs, c.pool)
1-element CategoricalArray{String,1,UInt32}:
 "test"
```
or
```
julia> CategoricalArray{Union{Missing,String},1}(c.refs, c.pool)
1-element CategoricalArray{Union{Missing, String},1,UInt32}:
 "test"
```
depending on what you want (just knowing `refs` and `pool` is not enough to answer which one you want AFAICT).

**Comment by evetion** [comment]
Ah, I did play around with the types, but tried to use `CategoricalVector` which doesn't work. Thanks for clearing it up (and so quickly as well)! For future reference, the code to create an CategoricalArray without conversion if you already have the raw values:

```julia
CategoricalArray{String,1}([0x01], CategoricalArrays.CategoricalPool(Dict("test" => 0x01)))
```
