### ISSUE TITLE
`hasmethod(isless, Tuple{T,T}) == true` when `T isa AbstractArray`

### ISSUE THREAD

**Issue by greimel** [JuliaData/CategoricalArrays.jl#291]
I want to store geographical units in a CategoricalVector. These geographical units are `GeometryBasics.MultiPolynomial <: AbstractVector`. One cannot compare geographical units. `m_poly1 < m_poly2` is not defined. Unfortunately `x::AbstractArray < y::AbstractArray` is defined, which is why `CategoricalArrays` wants to order them here (similar methods exist for tuples and pairs).

https://github.com/JuliaData/CategoricalArrays.jl/blob/cfbca7431e5b15ba93733a46aae8620c4afb89ea/src/array.jl#L346

Because of this, I guess one would need to add a `try ... catch` block for these containers and look for a MethodError right?

**Comment by bkamins** [comment]
@nalimilan - this is related to https://github.com/JuliaLang/julia/pull/36810#issuecomment-673627557 (and that is why I held back with defining a follow up PR to https://github.com/JuliaLang/julia/pull/36810).

I think that it would be better in the long term not to check `isless` but rather to use `OrderStyle` to determine if something can be ordered.

In short term I guess `try`-`catch` is the only reliable solution.

**Comment by nalimilan** [comment]
Yes, I agree. Actually in the short/medium term it should be quite easy to define an `OrderStyle` method for CategoricalArrays to avoid the need to call `hasmethod`. @greimel Would you be willing to make a PR to implement that?

**Comment by greimel** [comment]
Using `try ... catch`? If so, I could code up something.

I would leave the `OrderStyle` solution for the experts.

**Comment by nalimilan** [comment]
The idea would just be to replace the `hasmethod(isless, Tuple{L, L})` check with `Base.OrderStyle(L) isa Base.Ordered`.

**Comment by greimel** [comment]
I'll give it a try tomorrow.

**Comment by greimel** [comment]
fixed by #292
