### ISSUE TITLE
Working with missing values 

### ISSUE THREAD

**Issue by eloualiche** [JuliaData/CategoricalArrays.jl#298]
I am trying to estimate quantiles by groups on a dataset that has some missing using DataFrames. 
Unfortunately I have not found a good workaround to use `cut` in this environment.

Could we find a way to ignore missing (or `skipmissing`) on vectors such that the following command does not return an error:
```julia
cut([1, 2, missing], 2)
```

Ideally it would return a missing on the last component as in `R`:
```R
> cut(c(1,2,NA), 2)
[1] (0.999,1.5] (1.5,2]     <NA>
Levels: (0.999,1.5] (1.5,2]
```

**Comment by nalimilan** [comment]
Yes, `cut` should allow skipping values when calling `quantile`. Maybe a `skipmissing` keyword argument should be added. Though the name could be misleading as missing values are not skipped in general (they are propagated), but only for `quantile`. Maybe this should be the default, without any argument, as missing values are propagated so it's safe. Not sure.

Note that there's already an `allowmissing` argument which determines whether values outside of breaks should be replaced with `missing`.

For now you can achieve what you want by doing `cut(x, quantile(skipmissing(x), ...), extend=true)`.

**Comment by matthieugomez** [comment]
+1 for being the default.
