### ISSUE TITLE
`levelcode` doesn't seem to be documented

### ISSUE THREAD

**Issue by jkrumbiegel** [JuliaData/CategoricalArrays.jl#313]
I just followed a long chain of discourse posts and old PRs while trying to find out how to get the integer indices for categorical values corresponding to their position within their array's `levels`. At the end, I found that there is a `levelcode` function since January that does this, but I can't seem to find a mention of it in the docs. Should it be added?

**Comment by nalimilan** [comment]
Yes it should be mentioned somewhere in the docs.

**Comment by nalimilan** [comment]
See https://github.com/JuliaData/CategoricalArrays.jl/pull/338.
