### ISSUE TITLE
How about an alias DictTable for Dict{Symbol,AbstractVector{T}} where T

### ISSUE THREAD

**Issue by ablaom** [JuliaData/CategoricalArrays.jl#321]
We already have `ColumnTable` alias.

Our use case: wanting to give users option in an ML model to return either `ColumnTable` or `DictTable`;  first is in the Tables.jl namespace but second is not. 

Happy to make a PR.

@OkonSamuel

**Comment by bkamins** [comment]
This is probably a wrong repository to open this issue (rather Tables.jl is the right place).

Also note that `for Dict{Symbol,AbstractVector{T}} where T` is Tables.jl table.

**Comment by ablaom** [comment]
Oops 😳
