### ISSUE TITLE
views of a categorical arrays

### ISSUE THREAD

**Issue by ablaom** [JuliaData/CategoricalArrays.jl#324]
Currently a view of a categorical array is not an instance of `AbstractCategoricalArray`. Is there a reason for this?

@jeremiedb

**Comment by bkamins** [comment]
AFAICT the reason is that Julia does not allow multiple inheritance, but it was @nalimilan who designed it.

You have `CategoricalArrays.CatArrOrSub` defined in CategoricalArrays.jl that allows to check if some array is either `CategoricalArray` or its view.

**Comment by ablaom** [comment]
Right. 

And I do have 

```
julia> v = categorical(['a', 'b', 'a'])
julia> view(v, 1:2) isa AbstractArray{<:CategoricalArrays.CategoricalValue}
```
which is probably what I'm looking for anyway.

Thanks.

**Comment by bkamins** [comment]
Better use `CategoricalArrays.CatArrOrSub` (or parts of its definition), as `AbstractArray{<:CategoricalArrays.CategoricalValue}` can be eg. `Vector` holding `CategoricalValue` elements which does not follow the API of CategoricalArrays.jl.

**Comment by nalimilan** [comment]
OTOH `CatArrOrSub` isn't documented, has a ugly name and cannot be extended by other packages (even if that an unlikely need)... :-/ I wish we had a better solution.
