### ISSUE TITLE
add levelcode to the manual

### ISSUE THREAD

**Issue by bkamins** [JuliaData/CategoricalArrays.jl#335]
https://github.com/JuliaData/CategoricalArrays.jl/issues/228#issuecomment-811291782

> `levelcode` is missing in https://categoricalarrays.juliadata.org/latest/functionindex.html which makes it difficult to find.

**Comment by nalimilan** [comment]
Dup of https://github.com/JuliaData/CategoricalArrays.jl/issues/313.
