### ISSUE TITLE
recode can be too slow

### ISSUE THREAD

**Issue by pgagarinov** [JuliaData/CategoricalArrays.jl#343]
On the following screenshot I compare performance of `recode(cat_data_vec, cat_vec=>"None")` for 2 cases:
a) cat_vec is a categorical array
b) cat_vec is a string array

It turns out that performance of a) is significantly lower

<img width="483" alt="image" src="https://user-images.githubusercontent.com/4868370/114410307-f06c1b00-9bb3-11eb-917a-c688d48c852e.png">

It is not easy to reproduce the real scale of performance differences on artificial data, by on real data (300k records and 30k unique categories) case a) is actually 10 times slower (40 seconds) than b) (4 seconds).

**Comment by nalimilan** [comment]
The code has been optimized for a relatively small number of levels. Maybe this could be improved, but I'm not sure `recode` is the best tool for this task.

**Comment by pgagarinov** [comment]
> The code has been optimized for a relatively small number of levels. Maybe this could be improved, but I'm not sure `recode` is the best tool for this task.

Here is my use case - I have categorical features I use for ML and some categories are rare so I merge them into "None" category. I use categorical arrays because MLJ's API expects categorical features as categorical arrays.

**Comment by nalimilan** [comment]
Maybe a function similar to dplyr's `fct_collapse` would be more appropriate, and simpler to optimize.

That said, there are probably quite a few long-hanging fruits. Have you tried with master? Performance should already be better. You could try changing this line to do something like `sfirst = Set(first); recode_in(l, sfirst)`:
https://github.com/JuliaData/CategoricalArrays.jl/blob/b2177abe3c3170b91060800c5736f422121757bb/src/recode.jl#L182

**Comment by pgagarinov** [comment]
@nalimilan 
>Maybe a function similar to dplyr's fct_collapse would be more appropriate, and simpler to optimize.
This makes a perfect sense, such a function would perfectly fit my use case.

I've prepared some more representative data (attaching csv files).

Here are the results from the latest released version 0.9.5:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/4868370/115116726-dbbcc800-9fa3-11eb-93da-d9eecbc91955.png">

This is the result for the master (btw, the version of CategoricalArray in master is 0.9.3 which doesn't make much sense)

<img width="408" alt="image" src="https://user-images.githubusercontent.com/4868370/115116752-00b13b00-9fa4-11eb-9cbc-098dcd0985c1.png">

Thus `recode` in the master is almost 2 time faster than in 0.9.5 but it is still at least two times slower when categorical values to `recode` are provided as a categorical array as opposed to being given as a vector of strings.

>You could try changing this line to do something like sfirst = Set(first); recode_in(l, sfirst):

I've made the change you've suggested but it doesn't seem to help much, maybe just a tiny bit:

<img width="395" alt="image" src="https://user-images.githubusercontent.com/4868370/115117055-694ce780-9fa5-11eb-9432-a034adfd9754.png">


The data used in the test:
[recode_performance_test_data.zip](https://github.com/JuliaData/CategoricalArrays.jl/files/6329421/recode_performance_test_data.zip)

**Comment by nalimilan** [comment]
OK. Some profiling is needed to check where most of the time is spent.

(Could you copy/paste code instead of screenshots? That's much easier to reproduce.)

**Comment by nalimilan** [comment]
Actually the most important line is probably this one:
https://github.com/JuliaData/CategoricalArrays.jl/blob/b2177abe3c3170b91060800c5736f422121757bb/src/recode.jl#L229

On master, you could try doing simply `recode(orig_vec, Set(cat2merge_vec) => "None")`, that should have the same effect as modifying the function.

**Comment by pgagarinov** [comment]
>Could you copy/paste code instead of screenshots? That's much easier to reproduce.
Sure

```
using CategoricalArrays;
using DelimitedFiles;
orig_vec = readdlm("orig_vec.csv");
cat2merge_vec = readdlm("cat2rep_vec.csv");
orig_vec = categorical(orig_vec);
cat2merge_vec = categorical(cat2merge_vec);
@time recode(orig_vec, cat2merge_vec=>"None");
@time recode(orig_vec, cat2merge_vec=>"None");
@time recode(orig_vec, string.(cat2merge_vec)=>"None");
@time recode(orig_vec, string.(cat2merge_vec)=>"None");
```

**Comment by pgagarinov** [comment]
> Actually the most important line is probably this one:
> 
> https://github.com/JuliaData/CategoricalArrays.jl/blob/b2177abe3c3170b91060800c5736f422121757bb/src/recode.jl#L229
> 
> On master, you could try doing simply `recode(orig_vec, Set(cat2merge_vec) => "None")`, that should have the same effect as modifying the function.

That makes a huge difference:
```
julia> @time recode(orig_vec, Set(cat2merge_vec) => "None");
  0.015400 seconds (29.54 k allocations: 3.789 MiB)
```

**Comment by nalimilan** [comment]
Cool. So maybe we could always create a `Set` when `first` is a vector. Would you make a pull request?
