### ISSUE TITLE
Adding a function for releveling factor levels

### ISSUE THREAD

**Issue by kliegl** [JuliaData/CategoricalArrays.jl#368]
The flexible specification of the order of levels of a categorical variable (factor) is essential for the analysis of data from experimental designs. Indeed, in StatsModels.jl, contrast specification allows such a reordering levels. For a example, for a factor Condition with levels A to D we can relevel with:

`cntrst = Dict(:Condition => SeqDiffCoding(; levels=["B", "A", "D", "C"]))`

For _HypothesisCoding()_ there is also  the option of attaching informative labels for the output. Such a function would greatly facilitate generation of summary tables and plots.

Would you consider adding such a *relevel()* function to CategoricalArrays?

Thank you very much for your work on this package and your consideration of this question.

**Comment by bkamins** [comment]
If I understand correctly what you ask for this is already possible with `levels!` function:
```
julia> using CategoricalArrays

julia> x = categorical(["a", "b", "c", "a"])
4-element CategoricalArray{String,1,UInt32}:
 "a"
 "b"
 "c"
 "a"

julia> levels(x)
3-element Vector{String}:
 "a"
 "b"
 "c"

julia> levels!(x, ["c", "a", "b"])
4-element CategoricalArray{String,1,UInt32}:
 "a"
 "b"
 "c"
 "a"

julia> levels(x)
3-element Vector{String}:
 "c"
 "a"
 "b"
```
Is this what you want?

**Comment by kliegl** [comment]
Yes, simple enough. I thought I had tried _levels()_ before and did not get it. Thank you!

**Comment by kliegl** [comment]
Sorry, but your solution does not work if x is a variable in data frame.

**Comment by bkamins** [comment]
It should not make any difference. Can you please give an example of your code that fails?

**Comment by kliegl** [comment]
```
julia> dat = DataFrame("Condition" => ["A", "B", "C", "D", "A", "B", "C", "D"],
                       "Y" => 1:8)
8×2 DataFrame
 Row │ Condition  Y     
     │ String     Int64 
─────┼──────────────────
   1 │ A              1
   2 │ B              2
   3 │ C              3
   4 │ D              4
   5 │ A              5
   6 │ B              6
   7 │ C              7
   8 │ D              8

julia> levels(dat.Condition)
4-element Vector{String}:
 "A"
 "B"
 "C"
 "D"

julia> levels!(categorical(dat.Condition), ["C", "A", "D", "B"])
8-element CategoricalArray{String,1,UInt32}:
 "A"
 "B"
 "C"
 "D"
 "A"
 "B"
 "C"
 "D"

julia> levels(dat.Condition)
4-element Vector{String}:
 "A"
 "B"
 "C"
 "D"
```

**Comment by bkamins** [comment]
You are using `levels!` on a column that is not stored in a data frame.

Do the following:
```
dat = DataFrame("Condition" => categorical(["A", "B", "C", "D", "A", "B", "C", "D"]),
                            "Y" => 1:8)
```
and then:
```
levels!(dat.Condition, ["C", "A", "D", "B"])
```

**Comment by kliegl** [comment]
> @kliegl I thought you were interested in convenience functions similar to those provided by forcats? That's a separate issue.

That is correct and still true, but I was told that a request such for the equivalent of _fct_reorder()_ or _fct_reorder2()_ would be sacrilegious to the spirit of Julia programming. So I restricted myself to _relevel()_. It turns out after some clarification the solution is close enough to "convenient".   

> A related issue is the ability to attach contrasts to a variable so that you don't have to repeat them each time you fit a model. But this is better discussed in StatsModels as would require changes there, and the contrasts wouldn't necessarily be specific to CategoricalArray objects.

Personally, I advocate that  contrasts be specified explicitly, not implicitly. So on this account, I don't see so much of a need.

**Comment by nalimilan** [comment]
> That is correct and still true, but I was told that a request for the equivalent of _fct_reorder()_ or _fct_reorder2()_ would be sacrilegious to the spirit of Julia programming. So I restricted myself to _relevel()_. It turns out after some clarification the solution is close enough to "convenient".

Well, it depends. We already have a `levels!` method to change the order of levels by passing them explicitly, and `recode` to merge some levels. But we probably lack some convenience methods, though. Please file issues when you find a use case which isn't convenient enough currently.
