### ISSUE TITLE
precompile error when loading from other module

### ISSUE THREAD

**Issue by mkborregaard** [JuliaData/CategoricalArrays.jl#39]
When I load modules `RCall` or `MixedModels` (that both import CategoricalArrays) I get the error 
```
WARNING: Module CategoricalArrays with uuid 102572555498720 is missing from the cache.
This may mean module CategoricalArrays does not support precompilation but is imported by a module that does.
ERROR: LoadError: Declaring __precompile__(false) is not allowed in files that are being precompiled.
 in require(::Symbol) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in require(::Symbol) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in eval(::Module, ::Any) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/michael/.julia/v0.5/RCall/src/RCall.jl, in expression starting on line 3
ERROR: Failed to precompile RCall to /Users/michael/.julia/lib/v0.5/RCall.ji.
 in compilecache(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in require(::Symbol) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in require(::Symbol) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
```

**Comment by nalimilan** [comment]
That's weird, as I don't get any errors here. Are you using the latest versions of all packages? I've seen this error message a few times about various packages, and it usually goes away after a few attempts.

**Comment by nalimilan** [comment]
@dmbates Have you ever seen this?

**Comment by dmbates** [comment]
I don't get such errors with julia-0.5.0  I do get similar errors under julia-0.6.0-dev but they are attributed to `Iterators`, not `CategoricalArrays`.

**Comment by mkborregaard** [comment]
Sorry for not posting all the info - I am on Julia 0.5, CategoricalArrays 0.1.0. This seemed to be a conflict with package loaded in the workspace. Whenever I have been away from Julia for some time and run Pkg.update I also run a recompile function that loads all updated packages in turn. The problem persisted in that session, but disappeared after restarting Julia. Should I just close?

**Comment by nalimilan** [comment]
> I also run a recompile function that loads all updated packages in turn

You mean a custom function? Then it might be that Julia gets confused about the state of the cache. You should probably ask on the mailing list, or file an issue against Julia.

**Comment by mkborregaard** [comment]
Sort of, this one: https://github.com/JuliaLang/julia/issues/16409#issuecomment-228873060
