### ISSUE TITLE
`ordered` vs `ordinal`

### ISSUE THREAD

**Issue by alecloudenback** [JuliaData/CategoricalArrays.jl#398]
Maybe the ship has sailed, but would `ordinal` be a clarifying terminology change? I was confused when I first saw the first call below because I thought `ordered=true` would be saying that the array is already sorted. 

```julia
x = CategoricalArray(["Old", "Young", "Middle", "Young"], ordered=true)
levels!(x, ["Young", "Middle", "Old"])
```

might become

```julia
x = CategoricalArray(["Old", "Young", "Middle", "Young"], ordinal=true)
order!(x, ["Young", "Middle", "Old])
```

**Comment by bkamins** [comment]
Well it is pre 1.0 release, but it would be quite a big change. Let us see what @nalimilan thinks 😄.

**Comment by ablaom** [comment]
I can see where this is coming from but must admit this never confused me, as an outside user.  I do like that `order!` is a verb while `levels!` is a noun. For my part however, I feel this is a very minor semantic point, and would prefer to avoid the substantial disruption.

**Comment by nalimilan** [comment]
The "ordered" terminology comes from R. Probably "ordinal" would have been a better term, but I'm not convinced that changing it now would be worth the breakage either. Note that in Julia the term referring to data that is already sorted would be... "sorted" (as in `searchsortedfirst` and `SortedDict`; see also [occurrences in packages](https://juliahub.com/ui/Search?q=sorted&type=code)).
