### ISSUE TITLE
Define functions like `levels` in StatsBase?

### ISSUE THREAD

**Issue by dmbates** [JuliaData/CategoricalArrays.jl#65]
I think the conversion from `DataArrays` to `CategoricalArrays` would be made easier if functions like `levels` were defined in a "Base" package of some sort and the individual packages defined methods for those functions.  The base package doesn't have to be `StatsBase` - it could be something like `FactorBase` that is specific to this data type.

At least my experience is that I end up defining `AbstractFactor` types and  functions like
```julia
@compat const AbstractFactor{V,R} = Union{NullableCategoricalVector{V,R},CategoricalVector{V,R},PooledDataVector{V,R}}

"""
    asfactor(f)

Return `f` as a AbstractFactor.

This function and the `AbstractFactor` union can be removed once `CategoricalArrays` replace
`PooledDataArray`
"""
asfactor(f::AbstractFactor) = f
asfactor(f) = pool(f)


"""
    levs(A::ReMat)

Return the levels of the grouping factor.

This is to disambiguate a call to `levels` as both `DataArrays`
and `CategoricalArrays` export it.
"""
function levs(A::ReMat)
    f = A.f
    isa(f, PooledDataArray) ? DataArrays.levels(f) : CategoricalArrays.levels(f)
end
```

If I have missed a better way of working around the same name being defined in different packages please let me know.

**Comment by nalimilan** [comment]
Yes, I think we need a fallback like `levels(x::Any) = sort!(unique(x))`. But I'm not sure where it should be defined: I was thinking of the (still to be created) AbstractTables package, but there are other options.

**Comment by kleinschmidt** [comment]
I'd vote for StatsBase or some categorical-data-specific base package. Putting it in AbstractTables doesn't make much sense to me.

**Comment by nalimilan** [comment]
Since there is no categorical-specific package, and creating one just for that would seem overkill, that means StatsBase then.

**Comment by Nosferican** [comment]
I would favor having a categorical data base package. StatsBase has `levelsmap`, `indexmap`, and `indicatormat` which are functions that are mostly used with categorical variables. A categorical base package could migrate these. It could also help with packages besides that work with categorical data besides CategoricalArrays. For example, `AbstractCategoricalVector` is package dependent (like `AbstractDataFrames`) rather than having it defined at a higher level like `AbstractDataTable`.

**Comment by nalimilan** [comment]
`levels` lives in DataAPI now, and we have `refarray` and such there too, so closing.

**Comment by dmbates** [comment]
Thanks.
