### ISSUE TITLE
How to make a DataFrame out of CategoricalArrays?

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaData/CategoricalArrays.jl#79]
I was trying to run

```julia
using DataFrames, CategoricalArrays
DataFrame(NullableCategoricalArray(["nihao","haha"]))
```
but it gives an error

> MethodError: Cannot `convert` an object of type CategoricalArrays.NullableCategoricalArray{String,1,UInt32} to an object of type DataFrames.DataFrame
> This may have arisen from a call to the constructor DataFrames.DataFrame(...),
> since type constructors fall back to convert methods.
> in DataFrames.DataFrame at base\sysimg.jl:24

so I am just wondering how to make an DataFrame out of CategoricalArrays. I am quite new to Julia so not sure how to fix it myself just yet.

**Comment by cjprybol** [comment]
Hi @xiaodaigh. Glad you're trying out Julia! You've passed the DataFrame constructor a single Vector, `NullableCategoricalArray(["nihao","haha"])`. The DataFrame constructor for the current release expects a Vector of Vectors, so you just need to wrap `NullableCategoricalArray(["nihao","haha"])` in a Vector with `[]`.

Here's an example:
```julia
julia> DataFrame(CategoricalArray(["nihao","haha"]))
ERROR: MethodError: Cannot `convert` an object of type CategoricalArrays.CategoricalArray{String,1,UInt32,String,Union{}} to an object of type DataFrames.DataFrame
This may have arisen from a call to the constructor DataFrames.DataFrame(...),
since type constructors fall back to convert methods.
Stacktrace:
 [1] DataFrames.DataFrame(::CategoricalArrays.CategoricalArray{String,1,UInt32,String,Union{}}) at ./sysimg.jl:24

julia> DataFrame([CategoricalArray(["nihao","haha"])])
2×1 DataFrames.DataFrame
│ Row │ x1      │
├─────┼─────────┤
│ 1   │ "nihao" │
│ 2   │ "haha"  │
```

The current master branch of Julia will actually handle this differently, as seen here:
```julia
julia> DataFrame(CategoricalArray(["nihao","haha"]))
1×2 DataFrames.DataFrame
│ Row │ x1    │ x2   │
├─────┼───────┼──────┤
│ 1   │ nihao │ haha │

julia> DataFrame([CategoricalArray(["nihao","haha"])])
2×1 DataFrames.DataFrame
│ Row │ x1    │
├─────┼───────┤
│ 1   │ nihao │
│ 2   │ haha  │
```

But you shouldn't have to worry about that difference until the next release. Hope that helps!

FYI the best place to get feedback on questions is [Discourse](https://discourse.julialang.org). There is a much larger and more active audience available to answer questions there than on any individual package.
