### ISSUE TITLE
Can't use DataFramesMeta.by with NullableCategoricalArrays

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaData/CategoricalArrays.jl#80]
[Please see this stackoverflow post](https://stackoverflow.com/questions/46354895/julia-how-to-do-a-by-with-columns-defined-as-categoricalarrays-nullablecategori?noredirect=1#comment79687023_46354895)

Basically I have loaded in a DataFrame using Feather.jl and then I tried to do 

`by[df, :some_categorical_array_col, df1->sum(df1[:some_value])`

it fails  with

> MethodError: Cannot `convert` an object of type String to an object of type CategoricalArrays.CategoricalValue{String,Int32}
> This may have arisen from a call to the constructor CategoricalArrays.CategoricalValue{String,Int32}(...),
> since type constructors fall back to convert methods.
> in by at DataFrames\src\groupeddataframe\grouping.jl:320
> in groupby at DataFrames\src\groupeddataframe\grouping.jl:92
> in DataArrays.PooledDataArray at base\sysimg.jl:24
> in DataArrays.PooledDataArray at DataArrays\src\pooleddataarray.jl:140
> in convert at NullableArrays\src\primitives.jl:258
> in copy! at base\abstractarray.jl:655

and I am new to Julia hence not sure how to fix it myself.

**Comment by cjprybol** [comment]
The current release of DataFrames is not compatible with CategoricalArrays.

In the error message you'll see these two lines:
> in DataArrays.PooledDataArray at base\sysimg.jl:24
> in DataArrays.PooledDataArray at DataArrays\src\pooleddataarray.jl:140

which references a different "categorical" array data structure that is still used by the current release of DataFrames. You'll either need to upgrade DataFrames to master or use the [DataArrays.jl](https://github.com/JuliaStats/DataArrays.jl) package instead.

**Comment by xiaodaigh** [comment]
So I should be using Pkg.checkout("Data frames") to get to master branch. Thanks for your help.
