### ISSUE TITLE
`levels=` for `categorical()`

### ISSUE THREAD

**Issue by alyst** [JuliaData/CategoricalArrays.jl#84]
IIUC currently `categorical()` doesn't support specifying levels.
Would it be possible to support `levels=` keyword parameter?
The use case is e.g. when "normalizing" the imported data with known hard-coded category values.
That would save one `levels!()` call and make the user code a little bit less error-prone.

Somewhat related use-case is to make the categorical/plain values column `A` in one data frame matching the categorical column `B` in another (i.e. same levels encoding).
Would it be possible to do this with something like `similar(A, B)`?

**Comment by nalimilan** [comment]
> IIUC currently categorical() doesn't support specifying levels.
> Would it be possible to support levels= keyword parameter?
> The use case is e.g. when "normalizing" the imported data with known hard-coded category values.
> That would save one levels!() call and make the user code a little bit less error-prone.

I've been hesitant to add this. `levels!(categorical(x), [...])` isn't actually longer than `categorical(x, levels=[...])`, so is that really useful now that `levels!` returns the `CategoricalArray`?



> Somewhat related use-case is to make the categorical/plain values column A in one data frame matching the categorical column B in another (i.e. same levels encoding).
> Would it be possible to do this with something like similar(A, B)?

What do you want to do exactly? Share the same `CategoricalPool` object, or just copy the levels? Do the columns already exist, or do you want to create a new column based on an existing one?

**Comment by alyst** [comment]
> levels!(categorical(x), [...]) isn't actually longer than categorical(x, levels=[...]), so is that really useful now that levels! returns the CategoricalArray?

From technical POV, with levels known at construction one can guarantee that the optimal reference type would be used; probably there's a little bit less memory traversing/(re)allocation overhead too.
From the user perspective it's a little bit confusing to allow compression and specify whether the levels are ordered, when the actual levels and their order are not known.

> What do you want to do exactly? Share the same CategoricalPool object, or just copy the levels? Do the columns already exist, or do you want to create a new column based on an existing one?

I had in mind the use case when both `A` and `B` already exist; `B` is already a proper `CategoricalArray`; and `similar(A, B)` should convert `A` (by copying, in most cases) into `CategoricalArray` that shares the pool with `B`.
An alternative option would be something like `categorical(A, pool(B))`.

**Comment by nalimilan** [comment]
> From technical POV, with levels known at construction one can guarantee that the optimal reference type would be used; probably there's a little bit less memory traversing/(re)allocation overhead too.
> From the user perspective it's a little bit confusing to allow compression and specify whether the levels are ordered, when the actual levels and their order are not known.

Mmm, yeah, I guess we could do that when `compress=true` (we can't to it by default since that would be type-unstable). Currently we indeed call `unique` to find out the levels first, which is wasteful if you already know them. So why not, if you want to make a PR.

> I had in mind the use case when both A and B already exist; B is already a proper CategoricalArray; and similar(A, B) should convert A (by copying, in most cases) into CategoricalArray that shares the pool with B.
> An alternative option would be something like categorical(A, pool(B)). Eventually the new categorical array should replace the old column in the data frame.

I must say shared pools is an area I haven't explored at lot API-wise since there didn't seem to be a lot of demand for it. We could certainly try to improve it. `similar` could indeed be used for that, but your suggestion doesn't seem to match the standard semantics of that function. That would rather be `copy!(similar(B, sharepool=true), A)`, right? Not the most practical solution for your use case.

Extending the constructors is another solution. I think I'd prefer adding this feature to `CategoricalArray` constructors, as opposed to `categorical` which is supposed to be a simple, high-level interface. The lowest-level constructor already takes a pool as an argument, we could just extend the other ones to do the same (with a default to an empty pool).

**Comment by alyst** [comment]
The pool of `A` doesn't need to be shared with `B`, just being equal would be enough as long as joins and sorts work the same. 
Actually, I have no strong API preference for this operation as long as it's high-level and exported, `copy!(similar(B, 0), A)` would be fine, something along `categorical(A, pool(B))` is just a little bit more explicit.

Ultimately, the motivation is to have some sort of rudimentary db integrity checks.
In R I had quite some subtle bugs due to silent mismatches between the levels of the factors in different dataframes.
Some of them would be much more easier to spot, had something like `categorical(A, pool(B))` (that would throw an error if A cannot be converted) be easily available.

**Comment by nalimilan** [comment]
> The pool of A doesn't need to be shared with B, just being equal would be enough as long as joins and sorts work the same.
> Actually, I have no strong API preference for this operation as long as it's high-level and exported, copy!(similar(B, 0), A) would be fine, something along categorical(A, pool(B)) is just a little bit more explicit.

`categorical(A, pool(B))` would definitely share pools if it existed. If you merely want to use the same levels, we need to find a different API. Maybe `copy!(similar(B; levels=true), A)` or `copy!(similar(B; keeplevels=true), A)`.

> Ultimately, the motivation is to have some sort of rudimentary db integrity checks.
> In R I had quite some subtle bugs due to silent mismatches between the levels of the factors in different dataframes.
> Some of them would be much more easier to spot, had something like categorical(A, pool(B)) (that would throw an error if A cannot be converted) be easily available.

What kind of bugs are you talking about? With CategoricalArrays, there shouldn't be bugs when the levels differ. If you want to check that levels are the same, just do `levels(A) == levels(B)`. More advanced features are only needed if you want to ensure that integer codes are the same or that pools are shared (which can increase efficiency for some operations).

**Comment by alyst** [comment]
> What kind of bugs are you talking about?

The bugs in the user code due to assuming data integrity without actually checking it. Not in the factors/categories implementation.
Sure, one can do `levels(A) == levels(B) || errors("Levels don't match")`, but it's easy to forget, and the code with all the necessary checks would look a little bit paranoid -- in the end it's not the production code passed through CI, but some ad hoc scripting for yet another dataset.

I'm rather thinking about tweaking API, such that some of the integrity constraints could be easily defined and implicitly checked.
`CategoricalArrays` is already a step forward from R since it provides non-nullable and typed factors.
What I am missing in R and would like to have in Julia is a command to easily impose same levels/same ordering of a factor to columns from the different frames (poor man's foreign key).
In addition to just being convenient, it would also implicitly check whether the data in both columns could be encoded with the given levels.

**Comment by nalimilan** [comment]
What kind of API do you suggest which wouldn't amount to calling voluntarily a checking function? Also I'm not sure I understand what you mean by "data integrity".

**Comment by alyst** [comment]
Well, the one I propose in this PR (`categorical(A, pool(B))` or alternatives) indeed requires voluntary calling, but at least the checks are automatic (upon the construction of categorical array).
By data integrity here I mean "referential integrity" (categorical column serves as a foreign key).
I would be happy if anyone have other suggestions regarding easy/implicit integrity checks.

To be less abstract about the use case, I'm analyzing mass spectrometery data.
The datasets have proteins, protein groups, peptides shared by protein groups, experiments, quantitations of protein groups and peptides in experiments etc -- so it's quite a relational database.
However, the data is provided not as an SQL database, but as a collection of txt files (tab-separated format), and it's just not practical to convert it to e.g. SQLite or do some O/R mapping, especially since experimental design changes from dataset to dataset.
Some of these tables are composed by human beings and so are prone to have typos/errors.
So I'm reading these files into data frames, and it would be nice to have an easy way of expressing that all the columns in all the tables that refer to e.g. experiment use the same category levels and so on.
The simpler these commands would be, the more readable would be the code.
Sorry for this lengthy OT.

**Comment by nalimilan** [comment]
As I noted above, I would support a PR adding a `levels` keyword argument to `categorical` since that can allow choosing the reference type without calling `unique`. I don't think the `CategoricalPool` objects need to be exposed/used for the use case you describe, so better keep it simple.

**Comment by alyst** [comment]
Would you support `copy!(similar(B), A)`?

**Comment by nalimilan** [comment]
No. Even if `similar` preserved levels by default (which is itself controversial), copying into it shouldn't fail if some values are not in the existing levels.  Lots of functions call `similar` and fill the result with completely different values from the original, and failing on these cases would make `CategoricalArray` basically unusable as a generic `AbstractArray`.

**Comment by alyst** [comment]
Ok, I finally see the problem; for some obscure reason it occurred to me that `CategoricalPool` doesn't allow the addition of new levels after creation. Indeed, if it's allowed the proposed behaviour doesn't make sense. Sorry for confusion.
Are there any alternative packages with read-only pools? `IndirectArrays.jl` is something like this, but IIUC it doesn't allow `setindex!()`. `PooledArrays.jl` seem to allow implicit pool extension by `setindex!(PooledArray, v)`.

Another option would be to introduce `readonly` parameter to `CategoricalPool`, so that any implicit addition of the levels (by `setindex!(CategoricalArray)`) are not allowed.

**Comment by nalimilan** [comment]
I guess we could introduce that kind of parameter to prevent implicit addition of new levels. Though I'd call it `strict`, `closed`, `fixed` or something like that.

**Comment by nalimilan** [comment]
`categorical` now accepts a `levels` keyword argument, which is more efficient than calling `levels!` after the fact since in the new design we have to recompute reference codes when reordering levels.
